### ISSUE TITLE
如果是多数据操作 使用 eventproxy 还适合 吗？

### ISSUE THREAD

**Issue by yumemor** [alsotang/node-lessons#103]
看了说明 等待几个回调都执行完毕 再来处理数据 那么这些数据之前一直存储在内存中 如果是多数据量 比如抓取淘宝的商品 这种方式还适用吗？

**Comment by alsotang** [comment]
如果数据量比较大的时候，应该用队列那一系列思维。这时候甚至应该用外部的存储了。

在 2016年6月20日 下午2:54，yangyu <notifications@github.com>写道：
