### ISSUE TITLE
https的图有办法下载吗？

### ISSUE THREAD

**Issue by rekcah1986** [alsotang/node-lessons#113]
求教

**Comment by alsotang** [comment]
我说不能的话，你信？

2016-09-02 10:36 GMT+08:00 高彬彬 <notifications@github.com>:

**Comment by Jerret321** [comment]
最简单的方式wget
node里面 使用request  就好了。 具体你查下资料吧

**Comment by rekcah1986** [comment]
嗯，已经找到了，谢谢
