### ISSUE TITLE
JavaScript块级作用域

### ISSUE THREAD

**Issue by dfsq1311** [alsotang/node-lessons#119]
ES6新增let关键字为JavaScript新增了块级作用域。

参考：http://es6.ruanyifeng.com/#docs/let#ES6的块级作用域

lesson11中有关”JavaScript 中，变量的局部作用域是函数级别的。不同于 C 语言，在 C 语言中，作用域是块级别的。 JavaScript 中没有块级作用域。“的说法应有所调整。

建议增加代码实例：

```
function foo() {
  for (let i = 0; i < 10; i++) {
    let value = "hello world";
  }
  console.log(i); // throw ReferenceError: i is not defined
  console.log(value);// 不执行
}
foo();
```

**Comment by alsotang** [comment]
![image](https://cloud.githubusercontent.com/assets/1147375/20738701/e83489c0-b6ef-11e6-8d3e-5e6dc887da5e.png)


好的，我更新了一下这里
