### ISSUE TITLE
使用 eventproxy 控制并发时为啥前几个获取不了comment和title

### ISSUE THREAD

**Issue by jkgeekJack** [alsotang/node-lessons#120]
后面的都能获取到

**Comment by Topppy** [comment]
> 注意，cnodejs.org 网站有并发连接数的限制，所以当请求发送太快的时候会导致返回值为空或报错。建议一次抓取3个主题即可。文中的40只是为了方便讲解。

可以采取增加请求间隔的措施来解决该问题。

**Comment by qianlfeg1st** [comment]
topicUrls.forEach(function (topicUrl, index) {
      setTimeout(function() {
        superagent.get(topicUrl)
          .end(function (err, sres) {
              ep.emit('topic_html', [topicUrl, sres.text]);
          });
      }, 300 * index);
    });

这样就行了

**Comment by freedomDR** [comment]
学习了
