### ISSUE TITLE
每个课程可不可以开个作业的文件夹？

### ISSUE THREAD

**Issue by happlex** [alsotang/node-lessons#17]
大家看完课程之后，可以把自己的实践成果上传上来（或者贴个链接）。
比如我看了课程3之后，就写了个这个玩意儿...
https://github.com/happlex/uncontrolled-spider
这样，高手无聊的时候可以给新手做些指导...
新手，也可以参考更多的程序，写出更好玩的程序！~

**Comment by longjh00** [comment]
@acwong00 请教一下，在获取积分之后，新的ep回调中怎么改变topics元素的值？没有对象指针的概念吧？我还转不过来。
