### ISSUE TITLE
lesson3 npm install问题

### ISSUE THREAD

**Issue by ccysfn** [alsotang/node-lessons#30]
代码如下:
u2@u2:~/lesson3$ npm install express superagent cheerio --save
npm WARN package.json lesson3@1.0.0 No description
npm WARN package.json lesson3@1.0.0 No repository field.
npm WARN package.json lesson3@1.0.0 No README data
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/home/u2/.nvm/versions/v0.12.0/bin/node" "/home/u2/.nvm/versions/v0.12.0/bin/npm" "install" "express" "superagent" "cheerio" "--save"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! shasum check failed for /tmp/npm-26345-15a11022/registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm ERR! Expected: 5b7723034dda4d262e5a46fb2c58d7cc22f71420
npm ERR! Actual:   06149d1adcd371438ac0e0cc360dc03bbb46a4cd
npm ERR! From:     https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/u2/lesson3/npm-debug.log
找不到是什么问题啊，作者。

**Comment by alsotang** [comment]
这..看起来很奇怪的问题，重装也不行吗

2015-03-02 10:51 GMT+08:00 ccysfn <notifications@github.com>:

**Comment by ccysfn** [comment]
重装多试了几次可以了，估计是墙的问题。

**Comment by alsotang** [comment]
用 http://cnpmjs.org/ 提供的服务就好了

2015-03-10 14:52 GMT+08:00 ccysfn <notifications@github.com>:

**Comment by ccysfn** [comment]
thx!
close this issue plz!

**Comment by alsotang** [comment]
you can close it by yourself.
