### ISSUE TITLE
lesson4，topics.map 方法不是很理解。

### ISSUE THREAD

**Issue by wy19901227** [alsotang/node-lessons#42]
你好，lesson 爬虫，写的原理明白，但是
topics = topics.map(function (topicPair) {
    // 接下来都是 jquery 的用法了
    var topicUrl = topicPair[0];
    var topicHtml = topicPair[1];
    var $ = cheerio.load(topicHtml);
    return ({
      title: $('.topic_full_title').text().trim(),
      href: topicUrl,
      comment1: $('.reply_content').eq(0).text().trim(),
    });
  });
这个数组的map方法是说，讲数组中的每个元素运行给定得函数，但是这个topicPair是什么意思？为什么它的0，1是topicUrl,topicHtml? 小白 不是很理解，希望可以解答下。

**Comment by wy19901227** [comment]
哥，求解答啊，你不解答 ，自学 者  不知道在哪搞定了。。

**Comment by alsotang** [comment]
这个问题推荐上 stackoverflow

2015-06-10 13:12 GMT+08:00 wy19901227 <notifications@github.com>:
