### ISSUE TITLE
lesson3 只能抓到<h1>not found. resolve domain error</h1>

### ISSUE THREAD

**Issue by sabrinaluo** [alsotang/node-lessons#53]
用浏览器打开时能看到所有内容的，但是用superagent只能抓取如题所示的一句话，尝试使用request模块去抓也是一样的结果
请问是什么原因呢，该如何解决呢？谢谢

**Comment by alsotang** [comment]
对了。最近网站在备案需要关闭网站，所以未登录用户无法访问，抱歉，我们这边的问题。

在 2015年8月13日 下午4:51，Sabrina <notifications@github.com>写道：
