### ISSUE TITLE
lesson7讲得不是很清楚

### ISSUE THREAD

**Issue by rdmclin2** [alsotang/node-lessons#56]
例如：开始的目标里的`main.js: 类似上文提到的 fibonacci 函数。`,结果后来也没有再提到main.js
例如：`mocha init f2e`   应该用`mocha init vendor`,因为例子里用的vendor文件夹
例如:   插入`<script src='chai.js'></script>`，这里也没讲怎么下载chai.js

抱歉新手，会有困惑。

**Comment by zhaozhiming** [comment]
没错，而且按照示例代码完全跑不起来，浏览器是空白的，请作者再修正一下呢，谢谢

**Comment by alsotang** [comment]
@elrrrrrrr 帮看看？

**Comment by elrrrrrrr** [comment]
我修改下 : P

**Comment by elrrrrrrr** [comment]
@rdmclin2 
1. main.js 里只定义了一个函数作为测试的对象，表述的不是很清楚，已经修改
2. 已经改为 `mocha init vendor`
3. chai 改为使用 github 文件地址，这样比较简单 : ) 

@zhaozhiming
1. 我这暂时还没有重现，如果问题依旧存在，提供一下报错信息

多谢两位 !59

**Comment by rdmclin2** [comment]
@elrrrrrrr 手动点赞:)

**Comment by aimer1124** [comment]
@elrrrrrrr @alsotang 
lesson7的README中没有把`chai`的src地址修改正确(https://cdn.rawgit.com/chaijs/chai/master/chai.js)，但源代码已经修改。如果有空可以同步修改下

未修改时，index.html访问页面console会报错，无法显示测试执行的结果
```
Refused to execute script from 'https://raw.githubusercontent.com/chaijs/chai/master/chai.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

**Comment by alsotang** [comment]
@aimer1124 好了 https://github.com/alsotang/node-lessons/commit/74ace7dc263ee904863c0a92c862f4f1bba32d53
