### ISSUE TITLE
lesson4爬虫只能爬一部分

### ISSUE THREAD

**Issue by KongRain** [alsotang/node-lessons#60]
lesson4的爬虫按照您的app.js中的代码写只能爬到部分标题：
![issue](https://cloud.githubusercontent.com/assets/12316506/9599136/ec7723e6-50c3-11e5-9ef9-6b31b2b9548e.png)
总是有一部分的标题和评论识别不出来，而且后续添加挑战部分的内容时，对应的评论者和积分也都是undefined。剩下的能识别出来的部分都是正常的。
请问是什么原因呢？如果只有我出现这种问题是与node的配置有关吗？

**Comment by alsotang** [comment]
做一下频率限制。可能是爬太快，被服务器拒绝访问了某几条。

在 2015年9月1日 下午4:15，孔祥宇 <notifications@github.com>写道：

**Comment by KongRain** [comment]
谢谢您的解答！已经解决了，引入了async 模块的 eachLimit 函数，限制了并发数量。

**Comment by sabrinaluo** [comment]
请问要限制到多少才能正常爬取呢？设置10s爬一个网页还是会有一些爬不到，出现ETIMEDOUT错误

**Comment by MaskWu** [comment]
我引入了async的eachLimit 但是还是只能爬去到一部分，题主可否说一下你最后是怎么解决的

**Comment by KongRain** [comment]
我的代码在这里 https://github.com/KongRain/nodeLearning/blob/master/practice/lesson4/app.js 你可以看下有没有帮助，这是lesson4的代码~

**Comment by MaskWu** [comment]
ok，非常感谢

**Comment by alsotang** [comment]
@KongRain 感谢

**Comment by 52cik** [comment]
我也被坑到了，async 大法好，多谢。:grin:

**Comment by alsotang** [comment]
嗯嗯。。我们社区先埋个教学坑，总好过实际情况中遇到。。

2015-11-26 16:22 GMT+08:00 楼教主 <notifications@github.com>:

**Comment by charlessong0** [comment]
谢谢！还以为是list里的链接没有爬完就开始读取了。
不过为什么链接爬取 和 读取 一定是按顺序执行的？求解答~

**Comment by 312024196** [comment]
还是无法解决 求解答~~~~

**Comment by jadestrong** [comment]
@echoyangyang  试了下上面KongRain的方法可以都取到，至少不会再报503的错误，应该是使用forEach发送请求太快了，一次性发送40个请求大部分都被拒绝了，但是使用async限制了下效果还可以，另外希望博主能够在课程里面中做个说明，不然出了问题都不知咋回事 @alsotang

**Comment by ryangun** [comment]
感谢博主，@KongRain也很棒哦！
