### ISSUE TITLE
lesson4 eventproxy 顺序问题

### ISSUE THREAD

**Issue by cpoopc** [alsotang/node-lessons#64]
获取首页的列表后,再获取详情页的信息.使用eventproxy无法保证顺序,是按获取详情页的数据后emit的顺序来的.
如果想要按首页获取到的列表顺序,是否有什么办法可以做到?

**Comment by albin3** [comment]
可以用after+group保证顺序
文档，http://html5ify.com/eventproxy/api.html#eventproxy__after

**Comment by cpoopc** [comment]
@albin3 thanks!!

**Comment by cpoopc** [comment]
@albin3 ...看了下,不懂怎么用....汗  刚学js,不太懂

**Comment by albin3** [comment]
@cpoopc 我之前写的例子…你看一下==#
https://github.com/albin3/eventproxy-example
