### ISSUE TITLE
lessons6  你们都跑通过了？

### ISSUE THREAD

**Issue by honger05** [alsotang/node-lessons#69]
````bash
$ istanbul cover _mocha
````

![image](https://cloud.githubusercontent.com/assets/8788044/11113725/23d9fefc-895a-11e5-85ab-b481e9df9ef8.png)

好像是 _mocha 里面的语法问题。

特意关注了下 mocha 和 istanbul 的版本，完全是运行 lessons 6 的代码。

**Comment by honger05** [comment]
好吧！  可能是 我用的 win 10 的问题， git bash 命令工具 和  cygwin 的 make 工具。

`_mocha.cmd `  是这样的：

````bash
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\mocha\bin\_mocha" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\mocha\bin\_mocha" %*
)
````

回去用 Mac 试下。

**Comment by alsotang** [comment]
sorry 啊。node 社区还在发展中，对于 win 的支持。。。我相信10年后一定会好起来

2015-11-12 16:37 GMT+08:00 honger <notifications@github.com>:

**Comment by XGHeaven** [comment]
@honger05 我觉得可能那是一个批处理文件（在mac下确实是node代码，不知道为啥在window成那个了），不能直接用Istanbul运行的，我觉得你可以找到运行程序的入口，直接引用那个js文件

**Comment by honger05** [comment]
用 Mac 跑通了，我一般两个系统都用。这得看我女朋友想玩哪台电脑。TAT~

我觉得是做了对 win 的兼容，所以在win下，`.bin` 下面会多出一个 xx.cmd 的批处理。直接运行是OK的。可能是被其他命令调用存在问题。

**Comment by honger05** [comment]
另外， `npm i superagent`  安装不了，依赖了自己？

`install Refusing to install superagent as a dependency of itself`

我去 spm 里面找了下，有这个包。但是我就是有病啊，就想用 npm 来装。

**Comment by alsotang** [comment]
superagent不会依赖自己的。。去看看它的 package.json 就能确认了。

你这个错误，应该是在 superagent 的文件夹下面运行 `npm i superagent` 产生的？


2015-11-13 0:42 GMT+08:00 honger <notifications@github.com>:

**Comment by honger05** [comment]
咦~~    我删那么快，也被你发现了啊。

当时觉得这个问题可能是 superagent 库的，就跑去那边提了。[#781](https://github.com/visionmedia/superagent/issues/781)

我是在 case-superagent 文件夹下运行的 `npm i superagent`

运行 `npm i superagent@1.4.0` 是 OK 的。

在其他目录下再建立一个 case-superagent 文件夹，在里面再运行 `npm i superagent` 是正常的。

**Comment by alsotang** [comment]
解决了的话，就关了那个 issue 吧。顺便说明一下原因

在 2015年11月13日 下午11:17，honger <notifications@github.com>写道：

**Comment by BuptStEve** [comment]
https://github.com/gotwarlost/istanbul/issues/13

貌似是路径的问题？

我在本地装了下 mocha 

```bash
$ npm i mocha
```

然后运行这个 
```bash
$ istanbul cover node_modules/mocha/bin/_mocha
```

就行了...
