### ISSUE TITLE
lesson7引用raw.githubusercontent.com上的chai.js在chrome中报错

### ISSUE THREAD

**Issue by huguangju** [alsotang/node-lessons#70]
https://github.com/alsotang/node-lessons/blob/master/lesson7/vendor/index.html#L11

```js
Refused to execute script from 'https://raw.githubusercontent.com/chaijs/chai/master/chai.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
tests.js:3 Uncaught ReferenceError: chai is not defined
```

> chrome  46.0.2490.86 (64-bit)  
> 在firefox和safari中没有问题

通过 https://rawgit.com/ 从 GitHub 中获取正确完整的 Content-Type headers，得到开发版 https://rawgit.com/chaijs/chai/master/chai.js 和压缩版 https://cdn.rawgit.com/chaijs/chai/master/chai.js 文件路径, 并在index.html作相应替换，以解决此问题。

**Comment by alsotang** [comment]
嗯嗯。我改一下

**Comment by alsotang** [comment]
我看了一下，这个地方如果下载运行的话，是可以运行的。而且我们项目里面本来就配了 chai.js。
html 里面的那个引用，本身就不是供大家在线查看时候使用的。

**Comment by allenGKC** [comment]
check the [https://cdnjs.com/libraries/chai](https://cdnjs.com/libraries/chai) and choose the cnd to replace the https://raw.githubusercontent.com/chaijs/chai/master/chai.js in index.html
