### ISSUE TITLE
lesson7 测试反馈运行报错

### ISSUE THREAD

**Issue by byr-gdp** [alsotang/node-lessons#74]
执行 `mocha-phantomjs index.html --ssl-protocol=any --ignore-ssl-errors=true`后提示

`An error occurred trying to launch phantomjs at "/usr/local/bin/phantomjs": Error: spawn /usr/local/bin/phantomjs ENOENT
You can specify an explicit path to phantomjs via the `-p` option.`

**Comment by alsotang** [comment]
没有装 phantomjs 的原因？

2015-12-09 14:35 GMT+08:00 Dapeng Gong <notifications@github.com>:

**Comment by byr-gdp** [comment]
@alsotang 试试，一开始以为装了 `mocha-phantomjs` 就行了 :)

**Comment by alsotang** [comment]
看报错嘛，再去看看 mocha-phantomjs 的文档

2015-12-09 17:00 GMT+08:00 Dapeng Gong <notifications@github.com>:

**Comment by muzi-8** [comment]
为什么我自己电脑在线安装 phantomjs　mocha-phantomjs　这两个库一直安装不成功？
错误信息如下：

Error making request.
Error: connect ETIMEDOUT 52.216.1.0:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.7-15 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.7-15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
