### ISSUE TITLE
lesson7

### ISSUE THREAD

**Issue by yuu2lee4** [alsotang/node-lessons#78]
我们首先搭建一个测试原型，用 mocha 自带的脚手架可以自动生成。

cd vendor            # 进入我们的项目文件夹
npm i -g mocha       # 安装全局的 mocha 命令行工具
mocha init .         # 生成脚手架

应该是在lesson7文件夹下执行
mocha init vendor

**Comment by alsotang** [comment]
这不一样吗？

**Comment by yuu2lee4** [comment]
mocha init 会报错。。。提示没有 path 参数

**Comment by alsotang** [comment]
![image](https://cloud.githubusercontent.com/assets/1147375/12164816/7d18c046-b553-11e5-8320-3394b45b7b7f.png)
