### ISSUE TITLE
闭包的一个坑,结果不是12345

### ISSUE THREAD

**Issue by yinzSE** [alsotang/node-lessons#79]
>闭包的一个坑
==========
```
for (var i = 0; i < 5; i++) {
  setTimeout(function () {
    console.log(i);
  }, 5);
}
```
上面这个代码块会打印五个 5 出来，而我们预想的结果是打印 1 2 3 4 5。

应该是 `0 1 2 3 4`

**Comment by WoHal** [comment]
for (var i = 0; i < 5; i++) {
  setTimeout(function (i) {
    console.log(i);
  }(i), 5);
}

**Comment by XGHeaven** [comment]
@WoHal 请不要误导，谢谢，你那样写成同步执行了

```
for (var i = 0; i < 5; i++) {
    setTimeout(function (i) {
        console.log(i);
    }, 5, i);
}
```

@yinzSE 这不是异步的坑，是你对js还不是很了解，你需要明白他的作用域之间的关系

**Comment by alsotang** [comment]
@WoHal 真坑啊你

**Comment by WoHal** [comment]
@alsotang  哈哈, 必须坑

**Comment by XGHeaven** [comment]
@WoHal :joy:

**Comment by yinzSE** [comment]
@XGHeaven 我的意思是, 我们预期的结果应该是 0 1 2 3 4, 而不是 1 2 3 4 5
i 是 从 0 开始的
![image](https://cloud.githubusercontent.com/assets/12208108/12269337/eab33ba4-b98b-11e5-99e4-f3af35e50af6.png)
因为使用闭包写 我们得到的也是 0 1 2 3 4

**Comment by XGHeaven** [comment]
@yinzSE 没懂。。

**Comment by yinzSE** [comment]
@XGHeaven 
我的意思就是这句话应该这么改下..
>上面这个代码块会打印五个 5 出来，而我们预想的结果是打印 <s>1 2 3 4 5</s> 0 1 2 3 4。

**Comment by XGHeaven** [comment]
哦，好吧😂我懂了

**Comment by alsotang** [comment]
噢噢，你是在跟我反映问题啊。。

2016-01-13 0:55 GMT+08:00 Xu Tianyang <notifications@github.com>:

**Comment by alsotang** [comment]
修正了

2016-01-13 11:56 GMT+08:00 alsotang <alsotang@gmail.com>:
